// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kHAj_ik3mnRo0KgUgeb4ityu35LctNg',
    appId: '1:254876104905:web:3af6167e6a7fb5a281f518',
    messagingSenderId: '254876104905',
    projectId: 'edulearn-5d921',
    authDomain: 'edulearn-5d921.firebaseapp.com',
    storageBucket: 'edulearn-5d921.firebasestorage.app',
    measurementId: 'G-49CD6PFBWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirZMUwD8qGtDMnmZKIXl-QxglynM-VJs',
    appId: '1:254876104905:android:bbb0c778b9677f4d81f518',
    messagingSenderId: '254876104905',
    projectId: 'edulearn-5d921',
    storageBucket: 'edulearn-5d921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUfWy51_8nFKm5f6uOr1rdvt7fhJqq9s',
    appId: '1:254876104905:ios:3685776ed9fa6cee81f518',
    messagingSenderId: '254876104905',
    projectId: 'edulearn-5d921',
    storageBucket: 'edulearn-5d921.firebasestorage.app',
    iosBundleId: 'com.example.tugasUas1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUfWy51_8nFKm5f6uOr1rdvt7fhJqq9s',
    appId: '1:254876104905:ios:3685776ed9fa6cee81f518',
    messagingSenderId: '254876104905',
    projectId: 'edulearn-5d921',
    storageBucket: 'edulearn-5d921.firebasestorage.app',
    iosBundleId: 'com.example.tugasUas1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kHAj_ik3mnRo0KgUgeb4ityu35LctNg',
    appId: '1:254876104905:web:aa62fcf6465c622181f518',
    messagingSenderId: '254876104905',
    projectId: 'edulearn-5d921',
    authDomain: 'edulearn-5d921.firebaseapp.com',
    storageBucket: 'edulearn-5d921.firebasestorage.app',
    measurementId: 'G-8T61100J9R',
  );
}
